name: Deploy to ECR

on:
 
  push:
    branches: 
      - main

jobs:
  build:
    name: Build Image
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - uses: aws-actions/configure-aws-credentials@master
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-2

    - name: Login to AWS ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@master

    - name: Build, tag, and push image to Amazon ECR
      env:
        API_ENDPOINT: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: engasumozu_hub
        IMAGE_TAG: latest
      run: |
        docker build --build-arg REACT_APP_API_ENDPOINT=$API_ENDPOINT -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG